[package]
name = "copper"
version = "0.2.1"
edition = "2024"

[dependencies]
num-bigint = "0.4"
num-rational = "0.4"
num-complex = "0.4"
num-traits = "0.2"
num-integer = "0.1.46"
colored = "3.0.0"
repl_lib = "0.3.2"
